security.basic.enable: false
management.security.enabled: false
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #uri: https://github.com/indikal/cxfspring-gradle
          uri: file:///data/workspace/github/cxfspring-gradle/src/config
          searchPaths: cxf-server-config
#uri: file:///data/workspace/github/cxfspring-gradle/src/config